### ISSUE TITLE
pelase update for to bech 32 

### ISSUE THREAD

**Issue by avaxchain** [datadef/ava-hd-wallet#1]

**Comment by mertgonul** [comment]
I'll try to update it this weekend.

You can follow developments about it here.

https://github.com/datadef/ava-hd-wallet/projects/1

**Comment by mertgonul** [comment]
@avaxchain I updated.

**Comment by mertgonul** [comment]
@avaxchain updated.

**Comment by mertgonul** [comment]
Also you can reach the latest version on NPM.

`npm install ava-hd-wallet`

**Comment by avaxchain** [comment]
selam Mert.. great work sir.. will try to promote  avamatic.com

and also have a domain avaxchain.com  will probably implement it there.

btw how much was the prize  you won for avamatic ..  if you dont mind to
tell?


selam

Mert Gönül <notifications@github.com> schrieb am So., 30. Aug. 2020, 21:26:
